<a href="https://colab.research.google.com/github/omkarmohite123/Assignment-4/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import metrics
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test.csv to test.csv

In [ ]:
url = '/content/train.csv'
df1 = pd.read_csv(url)
df1.head(3)

,ID,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0,0.95577,0.0,8.14,0,0.538,6.047,88.8,4.4534,4,307.0,21.0,306.38,17.28,14.8
1,1,0.02875,28.0,15.04,0,0.464,6.211,28.9,3.6659,4,270.0,18.2,396.33,6.21,25.0
2,2,1.22358,0.0,19.58,0,0.605,6.943,97.4,1.8773,5,403.0,14.7,363.43,4.59,41.3

In [ ]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's



"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's\n\n\n\n"

In [ ]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['test.csv']))
df2.head(3)

,ID,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0,0.10612,30.0,4.93,0,0.428,6.095,65.1,6.3361,6,300.0,16.6,394.62,12.40
1,1,0.34109,0.0,7.38,0,0.493,6.415,40.1,4.7211,5,287.0,19.6,396.90,6.12
2,2,12.24720,0.0,18.10,0,0.584,5.837,59.7,1.9976,24,666.0,20.2,24.65,15.69

In [ ]:
df1.describe()

,ID,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,199.500000,3.757191,10.970000,10.936425,0.072500,0.552817,6.292165,68.086000,3.819462,9.462500,403.797500,18.459000,359.455375,12.668525,22.475750
std,115.614301,9.155496,22.796261,6.848042,0.259639,0.115488,0.709923,28.386888,2.132445,8.687478,169.656816,2.148105,86.732906,7.207047,9.218611
min,0.000000,0.009060,0.000000,0.460000,0.000000,0.385000,4.138000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.920000,5.000000
25%,99.750000,0.077820,0.000000,5.130000,0.000000,0.449000,5.877500,42.375000,2.109150,4.000000,277.000000,17.400000,376.115000,6.990000,17.100000
50%,199.500000,0.242170,0.000000,8.560000,0.000000,0.532000,6.208500,76.950000,3.272100,5.000000,329.000000,18.950000,391.575000,10.875000,21.000000
75%,299.250000,3.543427,12.500000,18.100000,0.000000,0.624000,6.620500,93.825000,5.214600,24.000000,666.000000,20.200000,396.285000,16.910000,25.000000
max,399.000000,88.976200,95.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
df2.describe()

,ID,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000
mean,52.000000,3.100574,12.800000,11.984095,0.057143,0.562010,6.253181,70.469524,3.699209,9.961905,426.219048,18.472381,345.695333,12.667238
std,30.454885,6.099267,25.384978,6.854823,0.233229,0.118159,0.679369,27.410123,2.017964,8.814241,164.240090,2.227041,106.976156,6.912011
min,0.000000,0.013600,0.000000,1.320000,0.000000,0.392000,3.561000,6.800000,1.285200,1.000000,188.000000,12.600000,3.650000,1.730000
25%,26.000000,0.100840,0.000000,6.090000,0.000000,0.449000,5.949000,47.200000,2.063500,4.000000,300.000000,16.600000,373.660000,7.120000
50%,52.000000,0.290900,0.000000,9.900000,0.000000,0.544000,6.195000,78.100000,2.783100,5.000000,391.000000,19.100000,390.740000,12.260000
75%,78.000000,4.261310,12.500000,18.100000,0.000000,0.624000,6.631000,94.500000,5.116700,24.000000,666.000000,20.200000,395.620000,17.160000
max,104.000000,45.746100,100.000000,27.740000,1.000000,0.871000,7.929000,100.000000,9.220300,24.000000,711.000000,21.200000,396.900000,36.980000

In [ ]:
df1.isnull().sum()

ID         0
CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [ ]:
import numpy as np

# Import phi from train data set
phi = np.loadtxt('/content/train.csv', dtype='float', delimiter=',', skiprows=1,
                 usecols=tuple(range(1, 14)))
print(phi)

[[9.55770e-01 0.00000e+00 8.14000e+00 ... 2.10000e+01 3.06380e+02
  1.72800e+01]
 [2.87500e-02 2.80000e+01 1.50400e+01 ... 1.82000e+01 3.96330e+02
  6.21000e+00]
 [1.22358e+00 0.00000e+00 1.95800e+01 ... 1.47000e+01 3.63430e+02
  4.59000e+00]
 ...
 [6.65492e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.96900e+02
  1.39900e+01]
 [1.31170e-01 0.00000e+00 8.56000e+00 ... 2.09000e+01 3.87690e+02
  1.40900e+01]
 [6.46600e-02 7.00000e+01 2.24000e+00 ... 1.48000e+01 3.68240e+02
  4.97000e+00]]

In [ ]:
# Import y from train data set
y = np.loadtxt('/content/train.csv', dtype='float', delimiter=',', skiprows=1,
               usecols=14, ndmin=2)

print(y)

[[14.8]
 [25. ]
 [41.3]
 [18.4]
 [19.8]
 [20.6]
 [15. ]
 [13.4]
 [23.1]
 [19.8]
 [50. ]
 [22. ]
 [21.7]
 [ 5. ]
 [26.7]
 [ 8.3]
 [16.1]
 [20.2]
 [28.5]
 [20.8]
 [29.4]
 [24.3]
 [18.1]
 [22.1]
 [24. ]
 [39.8]
 [18.4]
 [27.1]
 [23.9]
 [24.5]
 [21.2]
 [19.2]
 [20. ]
 [29.6]
 [19.1]
 [10.5]
 [28.1]
 [29. ]
 [20.9]
 [20.6]
 [30.5]
 [22.4]
 [33.8]
 [16.6]
 [28.4]
 [19.6]
 [28.2]
 [13.5]
 [17.8]
 [14.2]
 [ 8.4]
 [13.1]
 [15.3]
 [22.9]
 [20.6]
 [14.4]
 [24.4]
 [22.4]
 [29.1]
 [19.2]
 [21. ]
 [ 7.4]
 [16.3]
 [21.7]
 [16.6]
 [20.3]
 [18.7]
 [13.6]
 [19.5]
 [27.5]
 [22.7]
 [24.5]
 [18.9]
 [15. ]
 [22.8]
 [50. ]
 [24.8]
 [23. ]
 [22.8]
 [20.6]
 [13.8]
 [31. ]
 [22. ]
 [32.4]
 [18.5]
 [41.7]
 [30.7]
 [30.1]
 [10.4]
 [ 8.8]
 [23.1]
 [28.7]
 [43.1]
 [23.9]
 [23.4]
 [13.1]
 [24.7]
 [16.1]
 [31.6]
 [24.2]
 [26.6]
 [30.8]
 [20. ]
 [17.6]
 [24.8]
 [30.1]
 [35.2]
 [10.4]
 [ 8.3]
 [22.6]
 [11.5]
 [28.7]
 [33.4]
 [44.8]
 [36.5]
 [23.5]
 [13.9]
 [32.9]
 [11.8]
 [11.3]
 [11.7]
 [17.1]
 [32. ]
 [19.9]
 [21.5]
 [21.7]
 [36. ]
 [50. ]
 [13.8]
 [28. ]
 [50. ]
 [48.3]
 [13.3]
 [19.8]
 [20.4]
 [12.8]
 [21.4]
 [20.7]
 [21.7]
 [19.6]
 [17.8]
 [21.4]
 [19.4]
 [29.8]
 [17.8]
 [23.2]
 [15.6]
 [50. ]
 [24.4]
 [13.3]
 [23. ]
 [34.9]
 [29.8]
 [13.4]
 [22.2]
 [19.4]
 [33.4]
 [10.2]
 [20.3]
 [20.5]
 [14.6]
 [10.8]
 [17.4]
 [24.8]
 [14.5]
 [18.4]
 [ 8.7]
 [23.2]
 [22.3]
 [18.9]
 [22.5]
 [28.4]
 [20. ]
 [23.1]
 [14.6]
 [29. ]
 [23.1]
 [22. ]
 [23.3]
 [20.9]
 [14.3]
 [16.8]
 [24.1]
 [50. ]
 [37.6]
 [21.9]
 [23. ]
 [20.7]
 [34.9]
 [17.7]
 [13.3]
 [20.1]
 [18.5]
 [15.6]
 [14.5]
 [18.3]
 [22.2]
 [24.1]
 [13.6]
 [35.4]
 [34.6]
 [17.5]
 [13.1]
 [15.2]
 [22.8]
 [16.7]
 [25. ]
 [45.4]
 [37.2]
 [20.6]
 [16.1]
 [15.4]
 [19. ]
 [46.7]
 [20. ]
 [19.7]
 [13.2]
 [31.2]
 [ 6.3]
 [25. ]
 [ 8.5]
 [18.2]
 [18.3]
 [25.3]
 [36.1]
 [20.5]
 [12.7]
 [13.8]
 [23.7]
 [18.2]
 [20.5]
 [33. ]
 [44. ]
 [23.6]
 [21.6]
 [ 7. ]
 [21.2]
 [35.1]
 [19.6]
 [16.5]
 [38.7]
 [17.8]
 [12.3]
 [23.3]
 [22.2]
 [23.3]
 [18.9]
 [13.1]
 [14.9]
 [17.1]
 [ 7.5]
 [18.6]
 [30.1]
 [16.4]
 [15.6]
 [19.4]
 [20.3]
 [18.6]
 [22.9]
 [21.6]
 [17.2]
 [ 9.5]
 [11.9]
 [46. ]
 [17.8]
 [20.1]
 [19.4]
 [23.4]
 [13.9]
 [19.1]
 [13. ]
 [23.7]
 [13.4]
 [24.4]
 [18.8]
 [50. ]
 [50. ]
 [20.1]
 [17.5]
 [17.5]
 [14.1]
 [21.1]
 [25. ]
 [21.9]
 [16.7]
 [19.3]
 [22. ]
 [19.3]
 [21.2]
 [24.7]
 [26.4]
 [12.7]
 [20.1]
 [22. ]
 [22.6]
 [25.2]
 [50. ]
 [ 8.5]
 [10.9]
 [19.5]
 [30.3]
 [14.4]
 [10.5]
 [23.2]
 [15.6]
 [ 5. ]
 [50. ]
 [19. ]
 [22.6]
 [19.9]
 [ 9.6]
 [29.9]
 [19.4]
 [23.8]
 [42.8]
 [28.7]
 [17.3]
 [24.3]
 [20.8]
 [15.7]
 [31.7]
 [17.2]
 [23.3]
 [11.9]
 [32.5]
 [13.8]
 [50. ]
 [18.5]
 [15.2]
 [20.4]
 [19.3]
 [ 7.2]
 [26.4]
 [17.1]
 [24.4]
 [48.8]
 [33.1]
 [10.9]
 [50. ]
 [18.7]
 [35.4]
 [23.1]
 [21.7]
 [21.8]
 [22. ]
 [22.9]
 [25. ]
 [11.8]
 [26.6]
 [17.9]
 [20.2]
 [24.8]
 [ 8.8]
 [21. ]
 [23.7]
 [23.9]
 [13.5]
 [50. ]
 [18.7]
 [12. ]
 [19.9]
 [21. ]
 [21.2]
 [17.4]
 [23.7]
 [26.6]
 [15.6]
 [16.8]
 [21.2]
 [13.4]
 [37.9]
 [12.5]
 [ 5.6]
 [43.8]
 [22.9]
 [ 7.2]
 [23.6]
 [23.9]
 [20.3]
 [27.5]
 [29.1]
 [21.4]
 [23.9]
 [31.5]
 [32.7]
 [22.6]
 [17.4]
 [32.2]
 [27. ]
 [36.2]
 [15.4]
 [17.2]
 [26.5]
 [23. ]
 [33.2]
 [27.9]
 [24.7]
 [19.5]
 [20.4]
 [22.5]]

In [ ]:
# Import phi_test from test data set
phi_test = np.loadtxt('/content/test.csv', dtype='float', delimiter=',',
                      skiprows=1, usecols=tuple(range(1, 14)))
print(phi_test)

[[1.06120e-01 3.00000e+01 4.93000e+00 ... 1.66000e+01 3.94620e+02
  1.24000e+01]
 [3.41090e-01 0.00000e+00 7.38000e+00 ... 1.96000e+01 3.96900e+02
  6.12000e+00]
 [1.22472e+01 0.00000e+00 1.81000e+01 ... 2.02000e+01 2.46500e+01
  1.56900e+01]
 ...
 [5.36000e-02 2.10000e+01 5.64000e+00 ... 1.68000e+01 3.96900e+02
  5.28000e+00]
 [1.04690e-01 4.00000e+01 6.41000e+00 ... 1.76000e+01 3.89250e+02
  6.05000e+00]
 [4.55587e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.54700e+02
  7.12000e+00]]

In [ ]:
# Add a cloloumn of 1s to right of phi and phi_test
phi_test = np.concatenate((phi_test, np.ones((105, 1))), axis=1)
phi = np.concatenate((phi, np.ones((400, 1))), axis=1)

In [ ]:
# Min Max scaling for phi and phi_test (Feature Engineering)
for i in range(0, 13):
    col_max = max(phi[:, i])
    col_min = min(phi[:, i])
    phi[:, i] = (phi[:, i] - col_min) / (col_max - col_min)
    phi_test[:, i] = (phi_test[:, i] - col_min) / (col_max - col_min)

In [ ]:
# Log scaling on y
y = np.log(y)
print(y)

[[2.69462718]
 [3.21887582]
 [3.7208625 ]
 [2.91235066]
 [2.98568194]
 [3.02529108]
 [2.7080502 ]
 [2.59525471]
 [3.13983262]
 [2.98568194]
 [3.91202301]
 [3.09104245]
 [3.07731226]
 [1.60943791]
 [3.28466357]
 [2.11625551]
 [2.77881927]
 [3.0056826 ]
 [3.34990409]
 [3.03495299]
 [3.38099467]
 [3.19047635]
 [2.89591194]
 [3.09557761]
 [3.17805383]
 [3.68386691]
 [2.91235066]
 [3.29953373]
 [3.17387846]
 [3.19867312]
 [3.05400118]
 [2.95491028]
 [2.99573227]
 [3.38777436]
 [2.94968834]
 [2.35137526]
 [3.33576958]
 [3.36729583]
 [3.03974916]
 [3.02529108]
 [3.41772668]
 [3.10906096]
 [3.5204608 ]
 [2.8094027 ]
 [3.34638915]
 [2.97552957]
 [3.33932198]
 [2.60268969]
 [2.87919846]
 [2.65324196]
 [2.12823171]
 [2.57261223]
 [2.72785283]
 [3.13113691]
 [3.02529108]
 [2.66722821]
 [3.19458313]
 [3.10906096]
 [3.37073817]
 [2.95491028]
 [3.04452244]
 [2.00148   ]
 [2.79116511]
 [3.07731226]
 [2.8094027 ]
 [3.01062089]
 [2.92852352]
 [2.61006979]
 [2.97041447]
 [3.314186  ]
 [3.12236492]
 [3.19867312]
 [2.93916192]
 [2.7080502 ]
 [3.12676054]
 [3.91202301]
 [3.21084365]
 [3.13549422]
 [3.12676054]
 [3.02529108]
 [2.62466859]
 [3.4339872 ]
 [3.09104245]
 [3.47815842]
 [2.91777073]
 [3.73050113]
 [3.42426265]
 [3.40452517]
 [2.34180581]
 [2.17475172]
 [3.13983262]
 [3.35689712]
 [3.763523  ]
 [3.17387846]
 [3.15273602]
 [2.57261223]
 [3.20680324]
 [2.77881927]
 [3.45315712]
 [3.18635263]
 [3.28091122]
 [3.42751469]
 [2.99573227]
 [2.8678989 ]
 [3.21084365]
 [3.40452517]
 [3.56104608]
 [2.34180581]
 [2.11625551]
 [3.11794991]
 [2.44234704]
 [3.35689712]
 [3.5085559 ]
 [3.80220814]
 [3.59731226]
 [3.15700042]
 [2.63188884]
 [3.49347266]
 [2.46809953]
 [2.42480273]
 [2.45958884]
 [2.83907846]
 [3.4657359 ]
 [2.99071973]
 [3.06805294]
 [3.07731226]
 [3.58351894]
 [3.91202301]
 [2.62466859]
 [3.33220451]
 [3.91202301]
 [3.87743156]
 [2.58776404]
 [2.98568194]
 [3.0155349 ]
 [2.54944517]
 [3.06339092]
 [3.0301337 ]
 [3.07731226]
 [2.97552957]
 [2.87919846]
 [3.06339092]
 [2.96527307]
 [3.39450839]
 [2.87919846]
 [3.14415228]
 [2.74727091]
 [3.91202301]
 [3.19458313]
 [2.58776404]
 [3.13549422]
 [3.55248683]
 [3.39450839]
 [2.59525471]
 [3.10009229]
 [2.96527307]
 [3.5085559 ]
 [2.32238772]
 [3.01062089]
 [3.02042489]
 [2.68102153]
 [2.37954613]
 [2.85647021]
 [3.21084365]
 [2.67414865]
 [2.91235066]
 [2.16332303]
 [3.14415228]
 [3.10458668]
 [2.93916192]
 [3.11351531]
 [3.34638915]
 [2.99573227]
 [3.13983262]
 [2.68102153]
 [3.36729583]
 [3.13983262]
 [3.09104245]
 [3.14845336]
 [3.03974916]
 [2.66025954]
 [2.82137889]
 [3.18221184]
 [3.91202301]
 [3.62700405]
 [3.08648664]
 [3.13549422]
 [3.0301337 ]
 [3.55248683]
 [2.87356464]
 [2.58776404]
 [3.00071982]
 [2.91777073]
 [2.74727091]
 [2.67414865]
 [2.90690106]
 [3.10009229]
 [3.18221184]
 [2.61006979]
 [3.56671182]
 [3.54385368]
 [2.86220088]
 [2.57261223]
 [2.72129543]
 [3.12676054]
 [2.81540872]
 [3.21887582]
 [3.81551211]
 [3.61630876]
 [3.02529108]
 [2.77881927]
 [2.73436751]
 [2.94443898]
 [3.84374416]
 [2.99573227]
 [2.98061864]
 [2.58021683]
 [3.44041809]
 [1.84054963]
 [3.21887582]
 [2.14006616]
 [2.90142159]
 [2.90690106]
 [3.2308044 ]
 [3.58629287]
 [3.02042489]
 [2.54160199]
 [2.62466859]
 [3.16547505]
 [2.90142159]
 [3.02042489]
 [3.49650756]
 [3.78418963]
 [3.16124671]
 [3.07269331]
 [1.94591015]
 [3.05400118]
 [3.55820113]
 [2.97552957]
 [2.80336038]
 [3.6558396 ]
 [2.87919846]
 [2.50959926]
 [3.14845336]
 [3.10009229]
 [3.14845336]
 [2.93916192]
 [2.57261223]
 [2.70136121]
 [2.83907846]
 [2.01490302]
 [2.92316158]
 [3.40452517]
 [2.79728133]
 [2.74727091]
 [2.96527307]
 [3.01062089]
 [2.92316158]
 [3.13113691]
 [3.07269331]
 [2.84490938]
 [2.2512918 ]
 [2.4765384 ]
 [3.8286414 ]
 [2.87919846]
 [3.00071982]
 [2.96527307]
 [3.15273602]
 [2.63188884]
 [2.94968834]
 [2.56494936]
 [3.16547505]
 [2.59525471]
 [3.19458313]
 [2.93385687]
 [3.91202301]
 [3.91202301]
 [3.00071982]
 [2.86220088]
 [2.86220088]
 [2.6461748 ]
 [3.04927304]
 [3.21887582]
 [3.08648664]
 [2.81540872]
 [2.9601051 ]
 [3.09104245]
 [2.9601051 ]
 [3.05400118]
 [3.20680324]
 [3.27336401]
 [2.54160199]
 [3.00071982]
 [3.09104245]
 [3.11794991]
 [3.22684399]
 [3.91202301]
 [2.14006616]
 [2.38876279]
 [2.97041447]
 [3.41114771]
 [2.66722821]
 [2.35137526]
 [3.14415228]
 [2.74727091]
 [1.60943791]
 [3.91202301]
 [2.94443898]
 [3.11794991]
 [2.99071973]
 [2.2617631 ]
 [3.39785848]
 [2.96527307]
 [3.16968558]
 [3.7565381 ]
 [3.35689712]
 [2.8507065 ]
 [3.19047635]
 [3.03495299]
 [2.75366071]
 [3.45631668]
 [2.84490938]
 [3.14845336]
 [2.4765384 ]
 [3.48124009]
 [2.62466859]
 [3.91202301]
 [2.91777073]
 [2.72129543]
 [3.0155349 ]
 [2.9601051 ]
 [1.97408103]
 [3.27336401]
 [2.83907846]
 [3.19458313]
 [3.88773031]
 [3.49953328]
 [2.38876279]
 [3.91202301]
 [2.92852352]
 [3.56671182]
 [3.13983262]
 [3.07731226]
 [3.08190997]
 [3.09104245]
 [3.13113691]
 [3.21887582]
 [2.46809953]
 [3.28091122]
 [2.88480071]
 [3.0056826 ]
 [3.21084365]
 [2.17475172]
 [3.04452244]
 [3.16547505]
 [3.17387846]
 [2.60268969]
 [3.91202301]
 [2.92852352]
 [2.48490665]
 [2.99071973]
 [3.04452244]
 [3.05400118]
 [2.85647021]
 [3.16547505]
 [3.28091122]
 [2.74727091]
 [2.82137889]
 [3.05400118]
 [2.59525471]
 [3.63495111]
 [2.52572864]
 [1.7227666 ]
 [3.77963382]
 [3.13113691]
 [1.97408103]
 [3.16124671]
 [3.17387846]
 [3.01062089]
 [3.314186  ]
 [3.37073817]
 [3.06339092]
 [3.17387846]
 [3.44998755]
 [3.48737508]
 [3.11794991]
 [2.85647021]
 [3.47196645]
 [3.29583687]
 [3.58905912]
 [2.73436751]
 [2.84490938]
 [3.27714473]
 [3.13549422]
 [3.50254988]
 [3.32862669]
 [3.20680324]
 [2.97041447]
 [3.0155349 ]
 [3.11351531]]

In [ ]:
# Function to calculate change in error function
def delta_w(p, phi, w):
    if p == 2:
        deltaw = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) -
                       np.dot(np.transpose(phi), y)) +
                  lambd * p * np.power(np.absolute(w), (p - 1)))
    if p < 2 and p > 1:
        deltaw = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) -
                       np.dot(np.transpose(phi), y)) +
                  lambd * p * np.power(np.absolute(w), (p - 1)) * np.sign(w))
    return deltaw

In [ ]:
# Dictionary containing filenames as keys and p as values
filenames = {'output.csv': 2.0,
             'output_p1.csv': 1.75,
             'output_p2.csv': 1.5,
             'output_p3.csv': 1.3
             }

In [ ]:
# For each item in this dictionary
for (fname, p) in filenames.items():
    # Set initial w to zeros
    w = np.zeros((14, 1))

    # Hyperparameter lambda value
    lambd = 0.2

    # Maximum step size
    t = 0.00012

    # Calculate new value of w
    w_new = w - t * delta_w(p, phi, w)

    i = 0
    # Repeat steps until error between consecutive w is less than threshold
    while(np.linalg.norm(w_new-w) > 10 ** -10):
        w = w_new
        w_new = w - t * delta_w(p, phi, w)
        i = i + 1

    # Load values of id
    id_test = np.loadtxt('/content/test.csv', dtype='int', delimiter=',',
                         skiprows=1, usecols=0, ndmin=2)

    # Calculate y for test data
    y_test = np.exp(np.dot(phi_test, w_new))

    # Save the ids and y
    np.savetxt(fname, np.concatenate((id_test, y_test), axis=1),
               delimiter=',', fmt=['%d', '%f'], header='ID,MEDV', comments='')